"""Load bmug2's own configuration for the MCP server.

Reads the *generated* ``backmeup.setup.sh`` inside a bin directory -
never ``backmeup.setup.sh.template``, which still contains the real
rsync/updatedb detection loops as live shell code.

A regex-based parser is safe here (not a security shortcut): every
line ``backmeup.configure.sh`` writes comes from its write-out loop,

    for curvar in BMU_DIRRSYNC BMU_DIRBACKUPS ... ; do
        val=""
        bmuSetIndirectVar "val" "$curvar"
        echo "${curvar}=\"$val\"" >> "${MY_PATH}/backmeup.setup.sh.new"
    done

which always emits ``VAR="already-resolved-literal-value"`` - no
``$()``, no nested ``${...}``, no multi-line values. If a value still
contains ``$`` or a backtick, the file was hand-edited with real shell
syntax after generation; refuse rather than silently misinterpret it.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from pathlib import Path

_ASSIGNMENT = re.compile(r'^([A-Za-z_][A-Za-z0-9_]*)="(.*)"$')

# Characters that would only appear in a value if the file contains real
# shell syntax rather than a plain resolved literal (see module docstring).
_UNSAFE_VALUE_CHARS = ("$", "`")


class ConfigError(Exception):
    """Raised when BMUG2_BIN_DIR/backmeup.setup.sh can't be found or parsed."""


@dataclass(frozen=True)
class Config:
    bin_dir: Path
    sync_dir: Path
    history_dir: Path
    index_dir: Path | None
    locate_cmd: str | None


def resolve_bin_dir(cli_value: str | None) -> Path:
    """--bin-dir wins over BMUG2_BIN_DIR; neither given is a hard error."""
    raw = cli_value or os.environ.get("BMUG2_BIN_DIR")
    if not raw:
        raise ConfigError(
            "No bmug2 bin directory given. Pass --bin-dir <path> or set "
            "BMUG2_BIN_DIR to the directory holding backmeup.sh and a "
            "backmeup.setup.sh generated by backmeup.configure.sh."
        )
    bin_dir = Path(raw).expanduser()
    if not bin_dir.is_dir():
        raise ConfigError(f"BMUG2_BIN_DIR does not exist or is not a directory: {bin_dir}")
    return bin_dir


def _parse_setup_file(setup_file: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for lineno, line in enumerate(
        setup_file.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        match = _ASSIGNMENT.match(line)
        if not match:
            # Lines that aren't simple VAR="value" (blank/comments already
            # skipped above) are unexpected in a configure.sh-generated
            # file; ignore rather than fail, in case of a trailing newline
            # quirk or similar - only *unsafe values* are a hard error.
            continue
        name, value = match.group(1), match.group(2)
        if any(ch in value for ch in _UNSAFE_VALUE_CHARS):
            raise ConfigError(
                f"{setup_file}:{lineno}: {name} contains '$' or a backtick - "
                "this looks like real shell syntax, not a value written by "
                "backmeup.configure.sh. Refusing to guess; please regenerate "
                "the file with backmeup.configure.sh."
            )
        values[name] = value
    return values


def load_config(bin_dir: Path) -> Config:
    setup_file = bin_dir / "backmeup.setup.sh"
    if not setup_file.is_file():
        raise ConfigError(
            f"No backmeup.setup.sh in {bin_dir}. Run backmeup.configure.sh "
            "there first (this is the same precondition every bmug2 script "
            "assumes)."
        )
    values = _parse_setup_file(setup_file)

    sync_dir = values.get("BMU_DIRRSYNC", "")
    history_dir = values.get("BMU_DIRBACKUPS", "")
    if not sync_dir or not history_dir:
        raise ConfigError(
            f"{setup_file} is missing BMU_DIRRSYNC/BMU_DIRBACKUPS - it doesn't "
            "look like a file backmeup.configure.sh generated."
        )

    index_dir_value = values.get("BMU_DIRDBLOCATE", "")
    locate_cmd = values.get("BMU_CMDLOCATE", "") or None

    return Config(
        bin_dir=bin_dir,
        sync_dir=Path(sync_dir),
        history_dir=Path(history_dir),
        index_dir=Path(index_dir_value) if index_dir_value else None,
        locate_cmd=locate_cmd,
    )
