"""MCP server exposing bmug2's operations as tools.

Read-only tools (status, locate, dry-run previews) carry
read_only_hint=true and never touch disk. Mutating tools (real backup,
archive, unarchive, migrate) carry destructive_hint=true so a
well-behaved client gates them behind confirmation; their descriptions
open with "MUTATING:" too, since not every client surfaces annotations
in its own consent UI yet. The server itself never enforces
preview-before-mutate sequencing - that's the client's job.
"""

from __future__ import annotations

import argparse
import sys

from mcp.server.mcpserver import MCPServer
from mcp.types import ToolAnnotations

from . import commands, locate, status
from .config import Config, ConfigError, load_config, resolve_bin_dir
from .models import (
    ArchivePreviewResult,
    ArchiveResult,
    BackupPreviewResult,
    BackupResult,
    LocateResult,
    MigrateResult,
    StatusResult,
    UnarchiveResult,
)

_READ_ONLY = ToolAnnotations(read_only_hint=True, destructive_hint=False, idempotent_hint=True)
_MUTATING_BACKUP = ToolAnnotations(read_only_hint=False, destructive_hint=True, idempotent_hint=False)
_MUTATING_ARCHIVE = ToolAnnotations(read_only_hint=False, destructive_hint=True, idempotent_hint=True)
_MUTATING_UNARCHIVE = ToolAnnotations(read_only_hint=False, destructive_hint=True, idempotent_hint=False)
_MUTATING_MIGRATE = ToolAnnotations(read_only_hint=False, destructive_hint=True, idempotent_hint=False)


def create_server(config: Config) -> MCPServer:
    server: MCPServer = MCPServer(name="bmug2", version="0.1.0")

    @server.tool(annotations=_READ_ONLY)
    def bmug2_status() -> StatusResult:
        """Per-project backup overview: last run, last change, snapshot
        count, and mirror/history sizes in bytes. Read-only."""
        return status.get_status(config)

    @server.tool(annotations=_READ_ONLY)
    def bmug2_locate(patterns: list[str]) -> LocateResult:
        """Search the current mirror, full history, and archived
        snapshots for one or more filename patterns. Read-only."""
        return locate.do_locate(config, patterns)

    @server.tool(annotations=_READ_ONLY)
    def bmug2_backup_preview(path: str) -> BackupPreviewResult:
        """Read-only. Preview what backing up `path` would copy, delete,
        and archive, without changing anything on disk."""
        return commands.run_backup_preview(config.bin_dir, path)

    @server.tool(annotations=_READ_ONLY)
    def bmug2_archive_preview(project: str, days: int = 180) -> ArchivePreviewResult:
        """Read-only. Preview which snapshots of `project` older than
        `days` (default 180) would be archived, without changing anything."""
        return commands.run_archive_preview(config.bin_dir, project, days)

    @server.tool(annotations=_MUTATING_BACKUP)
    def bmug2_backup(path: str) -> BackupResult:
        """MUTATING: backs up `path`, copying new/changed files into the
        mirror and moving changed/deleted files into a dated snapshot.
        Consider calling bmug2_backup_preview first."""
        return commands.run_backup(config.bin_dir, path)

    @server.tool(annotations=_MUTATING_ARCHIVE)
    def bmug2_archive(project: str, days: int = 180) -> ArchiveResult:
        """MUTATING: compresses `project`'s snapshots older than `days`
        (default 180) into .tar.gz files, verified against their contents
        before the original directory is removed. Consider calling
        bmug2_archive_preview first."""
        return commands.run_archive(config.bin_dir, project, days)

    @server.tool(annotations=_MUTATING_UNARCHIVE)
    def bmug2_unarchive(project: str, snapshot: str) -> UnarchiveResult:
        """MUTATING: restores an archived snapshot of `project` back to a
        live directory and removes the archive. `snapshot` may be given
        with or without its "B-" prefix."""
        return commands.run_unarchive(config.bin_dir, project, snapshot)

    @server.tool(annotations=_MUTATING_MIGRATE)
    def bmug2_migrate(project: str) -> MigrateResult:
        """MUTATING: one-time fix for a project still in the pre-bmug2
        nested mirror layout. An instant rename; refuses if there's
        nothing to migrate or the layout is ambiguous."""
        return commands.run_migrate(config.bin_dir, project)

    return server


def main() -> None:
    parser = argparse.ArgumentParser(prog="bmug2-mcp")
    parser.add_argument(
        "--bin-dir",
        help="Directory holding backmeup.sh and a backmeup.setup.sh "
        "generated by backmeup.configure.sh. Falls back to BMUG2_BIN_DIR.",
    )
    args = parser.parse_args()

    try:
        bin_dir = resolve_bin_dir(args.bin_dir)
        config = load_config(bin_dir)
    except ConfigError as exc:
        print(f"bmug2-mcp: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc

    server = create_server(config)
    server.run()


if __name__ == "__main__":
    main()
