"""MCP server exposing bmug2's read-only operations as tools.

v1 (this file) ships only read-only tools: status, locate, and dry-run
previews of backup/archive. Mutating tools (real backup, archive,
unarchive, migrate) land in a follow-up once these have seen real use -
see docs/CONTRIBUTING.md and the project README for the rest of bmug2.
"""

from __future__ import annotations

import argparse
import sys

from mcp.server.mcpserver import MCPServer
from mcp.types import ToolAnnotations

from . import commands, locate, status
from .config import Config, ConfigError, load_config, resolve_bin_dir
from .models import ArchivePreviewResult, BackupPreviewResult, LocateResult, StatusResult

_READ_ONLY = ToolAnnotations(read_only_hint=True, destructive_hint=False, idempotent_hint=True)


def create_server(config: Config) -> MCPServer:
    server: MCPServer = MCPServer(name="bmug2", version="0.1.0")

    @server.tool(annotations=_READ_ONLY)
    def bmug2_status() -> StatusResult:
        """Per-project backup overview: last run, last change, snapshot
        count, and mirror/history sizes in bytes. Read-only."""
        return status.get_status(config)

    @server.tool(annotations=_READ_ONLY)
    def bmug2_locate(patterns: list[str]) -> LocateResult:
        """Search the current mirror, full history, and archived
        snapshots for one or more filename patterns. Read-only."""
        return locate.do_locate(config, patterns)

    @server.tool(annotations=_READ_ONLY)
    def bmug2_backup_preview(path: str) -> BackupPreviewResult:
        """Read-only. Preview what backing up `path` would copy, delete,
        and archive, without changing anything on disk."""
        return commands.run_backup_preview(config.bin_dir, path)

    @server.tool(annotations=_READ_ONLY)
    def bmug2_archive_preview(project: str, days: int = 180) -> ArchivePreviewResult:
        """Read-only. Preview which snapshots of `project` older than
        `days` (default 180) would be archived, without changing anything."""
        return commands.run_archive_preview(config.bin_dir, project, days)

    return server


def main() -> None:
    parser = argparse.ArgumentParser(prog="bmug2-mcp")
    parser.add_argument(
        "--bin-dir",
        help="Directory holding backmeup.sh and a backmeup.setup.sh "
        "generated by backmeup.configure.sh. Falls back to BMUG2_BIN_DIR.",
    )
    args = parser.parse_args()

    try:
        bin_dir = resolve_bin_dir(args.bin_dir)
        config = load_config(bin_dir)
    except ConfigError as exc:
        print(f"bmug2-mcp: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc

    server = create_server(config)
    server.run()


if __name__ == "__main__":
    main()
